# Generated by Django 3.1.7 on 2021-03-29 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')], null=True)),
                ('text', models.CharField(max_length=280)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('secret_key', models.CharField(max_length=6)),
            ],
        ),
    ]
